### PR TITLE
Simple server cleanup

### PR DESCRIPTION
**Pull request by canndrew**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/30)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
I'd ignore this for now @vinipsmaker because some of it conflicts with your PR #18. I'll fix it up or close it later when that PR is merged.

**Comment by canndrew** [comment]
This should be good to go if checks pass.

**Comment by vinipsmaker** [comment]
> This should be good to go if checks pass.

The checks aren't running. Need to ping @rossmuir about it.

**Comment by vinipsmaker** [comment]
Can I close #27 given all commits there are present in this PR?

**Comment by vinipsmaker** [comment]
Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/30)_

**Pull request merged**
