### PR TITLE
Derive(Eq, PartialEq) for MappedSocketAddr and PubRendezvousInfo

### PR DESCRIPTION
**Pull request by canndrew**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/29)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/29)_

**Comment by vinipsmaker** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/29)_

**Comment by vinipsmaker** [comment]
> This branch is out-of-date with the base branch

@canndrew: Can you rebase this branch against `master`?

**Pull request merged**
