### PR TITLE
Bump net2 dependency to 0.2.22

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/41)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @vinipsmaker (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by vinipsmaker** [comment]
Any particular reason why this update is important/critical?

**Comment by ghost** [comment]
Definitely not critical, just fixes OpenBSD build.

**Comment by dirvine** [comment]
It's only an update to the net2 lib and not bumping this lib so just a cleanup, which is OK I feel anyway :-) 

I think the other PR's fix the openbsd build, this won't really change anything, but nice to have.

**Comment by dirvine** [comment]
I suspect this PR fixes openbsd @polezaivsani so we would need to do a version update there.https://github.com/maidsafe/config_file_handler/pull/5 if you do a version change PR there we can update and publish this on crates and you should be sorted.

**Comment by vinipsmaker** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/41)_

**Comment by vinipsmaker** [comment]
> Definitely not critical, just fixes OpenBSD build.

Okay, gonna accept the PR. Feel free to send more. Although I believe this could be solved by running `cargo update` locally on your build env. Changes on the `Cargo.toml` file are more useful to API changes (or critical bugfixes that we need to ensure it'll be applied on all systems).

**Comment by vinipsmaker** [comment]
@polezaivsani, this PR has become obsolete as I merged another (older) PR in `master` just a few secs ago. Can you rebase your PR against `master` so I can merge it? I can also do it for you if you like. Just let me know what you prefer.

**Comment by ghost** [comment]
Fresh off the HEAD!

**Comment by vinipsmaker** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/41)_

**Comment by vinipsmaker** [comment]
> Fresh off the HEAD!

Just waiting for CI to finish to merge the PR.

**Comment by vinipsmaker** [comment]
PR merged. Thanks for your contribution.

**Pull request merged**
