### PR TITLE
Use unwrap crate

### PR DESCRIPTION
**Pull request by canndrew**
This change is [Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/53)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/53)_

**Comment by dirvine** [comment]
Ah @vinipsmaker  You may have missed the chat, but we are not using this crate yet, until we have a dev team triage on it. So best not to use these PR's just yet. There are a couple of queries and different priorities right now.

**Comment by vinipsmaker** [comment]
@dirvine: Yes, I've missed that. I thought it'd be okay to merge these. What now? Revert changes?

**Comment by dirvine** [comment]
No worries @vinipsmaker  For now I would revert that and keep going with crust testing and stabilization for now. It's improving ton's so far. Nice work you and @canndrew

**Comment by vinipsmaker** [comment]
> For now I would revert that and keep going with crust testing and stabilization for now.

I've hit the GitHub's revert button and it created a new PR: https://github.com/maidsafe/nat_traversal/pull/54

**Pull request merged**
