### PR TITLE
initial implementation

### PR DESCRIPTION
**Pull request by vinipsmaker**
Based on the crust refactor API:
- https://github.com/maidsafe/rfcs/blob/master/proposed/0000-crust-refactor/nat-traversal-library.md
- https://github.com/maidsafe/rfcs/blob/ccea9e6e706f56f4f892a1b3a9210d15f1dfd0d9/proposed/0000-crust-refactor/nat-traversal-library.md

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/1)

### CODE REVIEW

**Comment by dirvine** [comment]
This looks like a good start to me

**Comment by vinipsmaker** [comment]
> This looks like a good start to me

I'm working on a second commit that mirrors changes introduced in https://github.com/maidsafe/crust/pull/513

Need a complete drop-in replacement. So the behaviour must be fully mimicked.

**Comment by dirvine** [comment]
Excellent @vinipsmaker  This will be a terrific start and then on to tcp and friends. Nice one and rapd progress, just what we exactly need right now. :+1:

**Comment by dirvine** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/holepunchserveraddr.rs, line 28 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1#-K9dbi_7p7UhvKRtuMra:-K9dbi_7p7UhvKRtuMrb:-1812435130) ([raw file](https://github.com/maidsafe/nat_traversal/blob/2129778a45364e94f060476348e807748a590ab0/src/holepunchserveraddr.rs#L28)):_
I don't think this needs only to be ipV4 also perhaps the protocol should be made available here (tcp udp etc.) 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1)_

**Comment by dirvine** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[src/mappedsocketaddr.rs, line 21 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1#-K9dc0epeIJ3xC76Ei-S:-K9dc0eqpat-l7eXUpvg:-871303635) ([raw file](https://github.com/maidsafe/nat_traversal/blob/2129778a45364e94f060476348e807748a590ab0/src/mappedsocketaddr.rs#L21)):_
Again not sure we need to only handle ipV4 here 

---

_[src/mappingcontext.rs, line 20 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1#-K9dcaVgBuVeMvQLWQ83:-K9dcaVhgZSzEDL_CFfv:-1411165556) ([raw file](https://github.com/maidsafe/nat_traversal/blob/2129778a45364e94f060476348e807748a590ab0/src/mappingcontext.rs#L20)):_
May need to consider dhcp leases here 

---

_[src/periodic_sender.rs, line 20 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1#-K9dchcvm-1la5T-5ZIz:-K9dchcvm-1la5T-5ZJ-:-1722376259) ([raw file](https://github.com/maidsafe/nat_traversal/blob/2129778a45364e94f060476348e807748a590ab0/src/periodic_sender.rs#L20)):_
look at hole punch attempts here, retry every 3 secs 5 times ? 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1)_

**Comment by vinipsmaker** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

_[src/holepunchserveraddr.rs, line 28 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1#-K9dbi_7p7UhvKRtuMra:-K9ejKtxj7Pb75LeU84X:1245693572) ([raw file](https://github.com/maidsafe/nat_traversal/blob/2129778a45364e94f060476348e807748a590ab0/src/holepunchserveraddr.rs#L28)):_
Agreed, but the "protocol" here should be pretty much just be TCP and UDP. uTP, for instance, doesn't make sense, as the only purpose of this server is to map/punch a socket. However, I'd like this change to happen in a later PR, with the TCP hole punch implementation.

---

_[src/mappingcontext.rs, line 20 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1#-K9dcaVgBuVeMvQLWQ83:-K9ejy82uTmw82uFaFmg:2001360691) ([raw file](https://github.com/maidsafe/nat_traversal/blob/2129778a45364e94f060476348e807748a590ab0/src/mappingcontext.rs#L20)):_
Care to elaborate?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/1)_

**Comment by vinipsmaker** [comment]
I registered @dirvine concerns (except for DHCP leases because the concern wasn't well explained) one the issue tracker: https://github.com/maidsafe/nat_traversal/issues

I think we can take a look at them after migrating crust to use this crate.

**Pull request merged**
