### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by canndrew**
Reenables the `unused` lint and cleans up the result.
Also, changes the return type of `PunchedUdpSocket::punch_hole` to return a `WResult`, this is the only change that will effect crust.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/27)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by vinipsmaker** [comment]
Can you rebase against `master` and ping me back?

**Comment by canndrew** [comment]
Right, I will after I've fixed the tests.

**Comment by vinipsmaker** [comment]
> Right, I will after I've fixed the tests.

Do not forget to ping me, as `GitHub` won't notify me of new commits or tests passing/failing.

**Comment by vinipsmaker** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/socket_utils.rs, line 22 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/27#-KAF4DNahef_FLeNY5NL:-KAF4DNb_s7EEBEg8a5e:1861123944) ([raw file](https://github.com/maidsafe/nat_traversal/blob/65edc7eb9542d77370be291becc48075c1bd7db0/src/socket_utils.rs#L22)):_
Do we need commented code?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/27)_

**Comment by vinipsmaker** [comment]
Reviewed 8 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/27)_

**Comment by vinipsmaker** [comment]
> This branch has conflicts that must be resolved

Please rebase against `master`.

**Pull request merged**
