### PR TITLE
Bump net2 dependency to 0.2.22

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/40)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @canndrew (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[Cargo.toml, line 10 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/40#-KBPCZ-qn4QWJGWbBJ6J:-KBPCZ-qn4QWJGWbBJ6K:-1905677675) ([raw file](https://github.com/maidsafe/nat_traversal/blob/6e00ca6d6410accd79e5c024d955a3983a45fe8d/Cargo.toml#L10)):_
Can you please split into two PR's. When we update a version we use a special format for commit messages (and PR title). This should be (without quotes)

"Version update to 0.0.4"

This message triggers a tag and documentation update.. If you can split the PR in two then it's good to merge and thanks very much for the contributions. 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/40)_

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[Cargo.toml, line 10 [r2]](https://reviewable.io:443/reviews/maidsafe/nat_traversal/40#-KBPCZ-qn4QWJGWbBJ6J:-KBPD6r2asmQ_S2JntvN:-829617555) ([raw file](https://github.com/maidsafe/nat_traversal/blob/6e00ca6d6410accd79e5c024d955a3983a45fe8d/Cargo.toml#L10)):_
In fact I am not sure we need a version update here as this will pick up the latest net2, so just a commit to update the net2 version is fine thanks. 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/40)_

**Comment by dirvine** [comment]
r? @dirvine (thanks for the update)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/nat_traversal/40#-:-KBPGOezN_Q_Jaw_e2lA:1360633520)_

**Comment by ghost** [comment]
hm, guess i can't amend these. i'll submit two fresh ones

**Comment by dirvine** [comment]
Go to you too late, you can amend with a push to your branch. Anyway I will wait on the new PR, all you need to is update teh net2 dep, the lib here does not need a version update just yet (as we use the ~) 

Thx again

**Comment by ghost** [comment]
I was curious about the version bump - though crust build would stumble upon two different tiny net2 versions... but that turns out to not be the case - clean build passes just fine. sorry for the fuss.

**Comment by dirvine** [comment]
No fuss, happy for all contributors to feel at home here, so work away and PR anything you feel helps. The team will give feedback and help out. I suspect a version bump is required for the config_file_handler though to grab those changes for bsd (again just use "Version update to XXX" in the PR with only the changelog updated and the single change in cargo.toml if you want. We will get to it very soon otherwise..

**Comment by ghost** [comment]
Do you think those version bumps would come at home? I'm fixing thing 
locally and would probably cover a whole bunch of the projects to work 
out a clean OpenBSD build. right now i'm pathcing local cargo paths 
where i need maidsafe-related bumps. If you're updating versions 
yourself semiregularly, it'd be easier to just let you do the bumps and 
i'll be commiting just the fixes. don't want to make much noise out of 
it.

**Comment by dirvine** [comment]
No worries at all we will get the version bumps done no problem. Be great to be all ok on bsd machines as well so nice work. Thanks again

**Pull request closed without merging**
