### PR TITLE
Add udp hole punch example. Some other fixes.

### PR DESCRIPTION
**Pull request by canndrew**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/nat_traversal/15)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by canndrew** [comment]
I forgot to push [this](https://github.com/sbstp/rust-igd/pull/20) upstream. These checks should pass now.

**Comment by vinipsmaker** [comment]
Tests seem to pass now. Is PR ready to be reviewed?

**Comment by canndrew** [comment]
Yeah it's ready. There'll be quite a lot more changes coming in the next PR though.

**Pull request merged**
